### ISSUE TITLE
SBUS Algorithm issue

### ISSUE THREAD

**Issue by MagmaTart** [NoNamedSelfDriveing/Drone#29]
SBUS 디코딩이 잘 되다가 어느 순간 정지하고, 정확히 6,795ms 후에 다시 재개됨이 반복.
정지될 때의 특징을 찾아보니, memcpy의 순서가 뒤집어져 있음을 볼 수 있었지만, 알고리즘상에서 그 이유를 찾지 못함.

**Comment by jigeria** [comment]
For문 또는 반복문을 사용해서 해봐요
